Add Bed models for common printers
VoronDesign/Voron-Extras pull request #3
Opened 2021-12-15 06:09 UTC by timmit99

Adding STL and Texture files for common printers for use with Super Slicer and Prusa Slicer.

2021-12-15 06:13 UTC, timmit99 commented
@VoronDesign/github-administrators This should be good, i think i got rid of all the names with spaces in them. Let me know what you think.

-Tim

2021-12-15 13:33 UTC, KiloQubit requested changes
Can you update Overview.png with the correct SW model?  It shows the entire frame in the overview image, but the actual model is just the bed.

2021-12-15 23:24 UTC, timmit99 commented
> Can you update Overview.png with the correct SW model? It shows the entire frame in the overview image, but the actual model is just the bed.

Should be all good!

2021-12-16 00:07 UTC, KiloQubit approved these changes

2021-12-16 00:07 UTC, merged